In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
brfss = pd.read_csv('preprocessed_final.csv')
df = brfss.drop(['Unnamed: 0'], axis=1)

df

,_STATE,LADULT1,SEXVAR,GENHLTH,PHYSHLTH,MENTHLTH,PRIMINSR,PERSDOC3,MEDCOST1,CHECKUP1,...,_SMOKER3,_RFSMOK3,_CURECI1,DRNKANY5,DROCDY3_,_DRNKWK1,_RFDRHV7,_FRTLT1A,_VEGLT1A,_RFBING5
0,1,1.0,2,5.0,20.0,10.0,3.0,1.0,2.0,2.0,...,3,1,1,2,0,0,1,1,1,1
1,1,1.0,2,3.0,88.0,88.0,1.0,2.0,2.0,1.0,...,4,1,1,2,0,0,1,1,1,1
2,1,1.0,2,2.0,88.0,88.0,2.0,2.0,2.0,1.0,...,4,1,1,2,0,0,1,1,2,1
3,1,1.0,2,2.0,88.0,10.0,2.0,1.0,2.0,1.0,...,4,1,1,1,14,300,1,1,1,2
4,1,1.0,1,5.0,30.0,88.0,3.0,1.0,2.0,1.0,...,4,1,1,2,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109188,78,1.0,2,1.0,88.0,88.0,1.0,2.0,2.0,1.0,...,4,1,1,2,0,0,1,9,1,1
109189,78,1.0,2,2.0,88.0,88.0,88.0,1.0,2.0,2.0,...,4,1,1,1,7,47,1,2,1,1
109190,78,1.0,2,2.0,88.0,88.0,3.0,1.0,2.0,1.0,...,4,1,1,2,0,0,1,1,1,1
109191,78,1.0,2,4.0,77.0,77.0,3.0,1.0,2.0,1.0,...,4,1,1,2,0,0,1,9,9,1
109192,78,1.0,2,3.0,77.0,88.0,3.0,1.0,2.0,1.0,...,4,1,1,2,0,0,1,1,2,1

In [8]:
print(stats.pearsonr(df['_MENT14D'], df['_RFBING5']))
# print(stats.spearmanr(df['_MENT14D'], df['_RFBING5']))

PearsonRResult(statistic=0.014567982533790411, pvalue=1.4786659069010227e-06)
SignificanceResult(statistic=0.045180882580725036, pvalue=1.8876374763642804e-50)

In [5]:
stats.pearsonr(df['_STATE'], df['_RFBING5'])

PearsonRResult(statistic=0.009415561965036519, pvalue=0.00186236634612609)

In [6]:
stats.pearsonr(df['ALCDAY5'], df['_MENT14D'])

PearsonRResult(statistic=0.040378166044874264, pvalue=1.2167402272345235e-40)

In [7]:
stats.pearsonr(df['_STATE'], df['_MENT14D'])

PearsonRResult(statistic=0.0004451456733159786, pvalue=0.8830579201403834)

In [12]:
cols = ['_STATE', 'SEXVAR', 'MENTHLTH', 'ADDEPEV3', 'ALCDAY5', '_MENT14D','DRNKANY5', 'DROCDY3_', 
        '_DRNKWK1', '_RFDRHV7', '_RFBING5']

mental_drink = df.loc[:, [x for x in cols if x.startswith(x)]]

mental_drink.corr()

,_STATE,SEXVAR,MENTHLTH,ADDEPEV3,ALCDAY5,_MENT14D,DRNKANY5,DROCDY3_,_DRNKWK1,_RFDRHV7,_RFBING5
_STATE,1.000000,-0.007716,0.001981,-0.009037,-0.003631,0.000445,-0.002718,-0.008206,0.003281,0.000436,0.009416
SEXVAR,-0.007716,1.000000,-0.101575,-0.060334,0.123419,0.057890,0.123606,-0.143277,-0.023003,-0.012253,-0.090773
MENTHLTH,0.001981,-0.101575,1.000000,0.205415,0.019998,-0.389740,0.022086,-0.000725,-0.005716,-0.016070,-0.050364
ADDEPEV3,-0.009037,-0.060334,0.205415,1.000000,-0.013108,-0.101716,-0.012342,0.009323,-0.002827,-0.008947,-0.017823
ALCDAY5,-0.003631,0.123419,0.019998,-0.013108,1.000000,0.040378,0.995941,-0.599870,-0.113945,-0.156050,-0.293173
_MENT14D,0.000445,0.057890,-0.389740,-0.101716,0.040378,1.000000,0.039819,-0.024055,0.014672,0.018171,0.014568
DRNKANY5,-0.002718,0.123606,0.022086,-0.012342,0.995941,0.039819,1.000000,-0.601424,-0.113804,-0.156513,-0.293255
DROCDY3_,-0.008206,-0.143277,-0.000725,0.009323,-0.599870,-0.024055,-0.601424,1.000000,0.113009,0.219962,0.338684
_DRNKWK1,0.003281,-0.023003,-0.005716,-0.002827,-0.113945,0.014672,-0.113804,0.113009,1.000000,0.956404,0.091716
_RFDRHV7,0.000436,-0.012253,-0.016070,-0.008947,-0.156050,0.018171,-0.156513,0.219962,0.956404,1.000000,0.194358
_RFBING5,0.009416,-0.090773,-0.050364,-0.017823,-0.293173,0.014568,-0.293255,0.338684,0.091716,0.194358,1.000000